name: CICD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - master
    - staging
    - develop
  pull_request:
    branches:
    - master
    - staging
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.5'
    
    - name: Install dependencies
      run: |
        go get -u golang.org/x/lint/golint
        
    - name: Run build
      run: go build . 
      
    - name: Run vet & lint
      run: |
        go vet .
        golint .
    
    - name: Run testing
      run: go test -v

  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }} 
    steps:
    - uses: actions/checkout@v2

    - name: Deploy to Docker registry
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: alex1x/gotest
        tag_with_ref: true